# Generated by Django 2.1.5 on 2019-02-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacao', '0002_auto_20190206_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
