# Generated by Django 2.1.5 on 2019-02-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacao', '0003_auto_20190206_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='data_hora',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
