# Generated by Django 2.1.5 on 2019-02-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacao', '0004_auto_20190207_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='email_contato',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nome',
        ),
    ]
